### ISSUE TITLE
Removed methods

### ISSUE THREAD

**Issue by cv65kr** [apisearch-io/php-client#109]
Methods like `getQuery`, `getFilters` doesn't exists anymore in https://github.com/apisearch-io/php-client/blob/master/Result/Result.php but is required in https://github.com/apisearch-io/php-client/blob/master/Url/UrlBuilder.php#L255

**Comment by mmoreram** [comment]
@cv65kr seems that this UrlBuilder is not used anymore. The Twig part should not be supported anymore, so if we really want to make it performant, the read part of the application should be always be implemented through JS library.

I will check it and delete the unused classes.
Thanks so much @cv65kr :D

**Comment by mmoreram** [comment]
Solved in https://github.com/apisearch-io/php-client/pull/110
